"""Initial schema: decisions, market, strategies, risk, orders

Revision ID: e4fe8a45245d
Revises: 
Create Date: 2026-08-29 10:50:47.763356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fe8a45245d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=False),
    sa.Column('market_regime', sa.String(length=32), nullable=False),
    sa.Column('iv30', sa.Float(), nullable=False),
    sa.Column('iv_rank', sa.Float(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('packet_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_index(op.f('ix_decisions_underlying'), 'decisions', ['underlying'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('iv30', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_id'), 'market_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_table('option_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('contract_symbol', sa.String(length=64), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('mid', sa.Float(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_snapshots_contract_symbol'), 'option_snapshots', ['contract_symbol'], unique=False)
    op.create_index(op.f('ix_option_snapshots_id'), 'option_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_option_snapshots_underlying'), 'option_snapshots', ['underlying'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('agent_role', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_decision_id'), 'agent_runs', ['decision_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=True)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_decision_id'), 'orders', ['decision_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('risk_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('budget_pass', sa.Boolean(), nullable=False),
    sa.Column('liquidity_pass', sa.Boolean(), nullable=False),
    sa.Column('concentration_pass', sa.Boolean(), nullable=False),
    sa.Column('check_details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_checks_decision_id'), 'risk_checks', ['decision_id'], unique=False)
    op.create_index(op.f('ix_risk_checks_id'), 'risk_checks', ['id'], unique=False)
    op.create_table('strategy_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('pop', sa.Float(), nullable=False),
    sa.Column('max_profit', sa.Float(), nullable=False),
    sa.Column('max_loss', sa.Float(), nullable=False),
    sa.Column('net_credit', sa.Float(), nullable=False),
    sa.Column('liquidity_score', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('legs_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_candidates_decision_id'), 'strategy_candidates', ['decision_id'], unique=False)
    op.create_index(op.f('ix_strategy_candidates_id'), 'strategy_candidates', ['id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_exec_id', sa.String(length=64), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_id'), 'fills', ['id'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_strategy_candidates_id'), table_name='strategy_candidates')
    op.drop_index(op.f('ix_strategy_candidates_decision_id'), table_name='strategy_candidates')
    op.drop_table('strategy_candidates')
    op.drop_index(op.f('ix_risk_checks_id'), table_name='risk_checks')
    op.drop_index(op.f('ix_risk_checks_decision_id'), table_name='risk_checks')
    op.drop_table('risk_checks')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_decision_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_decision_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_option_snapshots_underlying'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_id'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_contract_symbol'), table_name='option_snapshots')
    op.drop_table('option_snapshots')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_decisions_underlying'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
